added the separate section
recodehive/machine-learning-repos pull request #1206
Opened 2024-08-27 17:20 UTC by aditya-bhaumik

## Description

Please include a summary of the changes and the related issue. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes #1169 

## Type of change

- [ ] Added a new machine learning frameworks, libraries or software.
- [ ] Documentation update

## Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2024-08-27 17:25 UTC, vivekv2810 requested changes

2024-08-27 17:25 UTC, vivekv2810 commented on Website/styles.css
> +}
```suggestion
}
/* Dark Mode Styles */

.dark-mode .github-section{
    background-color: #8397fa;
}
```

2024-08-27 17:30 UTC, aditya-bhaumik commented
@sanjay-kv me and vivek worked on this pull request and the other ones as well

2024-08-27 17:30 UTC, vivekv2810 commented
Dark Mode:

![image](https://github.com/user-attachments/assets/537c260d-b079-461d-89b9-49c97aba7a3f)

![image](https://github.com/user-attachments/assets/a9831ace-cf6a-4d13-8651-42bf520f10b0)

![image](https://github.com/user-attachments/assets/9622350f-02bc-4bd6-8f52-2353d96880a4)

![image](https://github.com/user-attachments/assets/3d924057-1c7e-4060-8af7-12796766b50a)

Light Mode:

![image](https://github.com/user-attachments/assets/27672181-ca3d-4a5e-bad3-f3298b748aec)

2024-08-28 09:28 UTC, sanjay-kv approved these changes

2024-08-28 09:29 UTC, merged